//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SolidSBCSrvCfgGUI.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         101
#define IDS_ABOUTBOX                    101
#define IDD_SOLIDSBCSRVCFGGUI_DIALOG    102
#define IDS_PROFILE_HEADER_ATTRIBUTE_STRING 103
#define IDS_PROFILE_HEADER_VALUE_STRING 104
#define IDS_PROFILE_ID_STRING           105
#define IDS_PROFILE_NAME_STRING         106
#define IDS_PROFILE_HD_ENABLE_STRING    107
#define IDS_PROFILE_HD_RANDOM_READ_STRING 108
#define IDS_PROFILE_HD_RANDOM_WRITE_STRING 109
#define IDS_PROFILE_HD_READ_MAX_STRING  110
#define IDS_PROFILE_HD_WRITE_MAX_STRING 111
#define IDS_BUTTON_PROFILE_EDITOR_STRING 112
#define IDS_TITLE_VMPERFORMER_SERVER_DLG_STRING 113
#define IDS_PROFILE_HD_READWRITE_DELAY_STRING 114
#define IDS_PROFILE_HD_TRANSMIT_DATA_STRING 115
#define IDS_PROFILE_CPU_ENABLE_STRING   116
#define IDS_PROFILE_CPU_RANDOMIZE_STRING 117
#define IDS_PROFILE_CPU_MAX_RANDOM_STRING 118
#define IDS_PROFILE_CPU_MAX_SLEEP_STRING 119
#define IDS_PROFILE_CPU_THREAD_COUNT_STRING 120
#define IDS_PROFILE_CPUMEASURE_ENABLE_STRING 121
#define IDS_PROFILE_CPUMEASURE_ADDITION_COUNT_STRING 122
#define IDS_PROFILE_CPUMEASURE_DIVISION_COUNT_STRING 123
#define IDS_PROFILE_CPUMEASURE_TRANSMIT_DATA_STRING 124
#define IDS_PROFILE_CPUMEASURE_FIX_MULTI_STRING 125
#define IDS_PROFILE_CPUMEASURE_FIX_MULTI_THRESHOLD_STRING 126
#define IDS_PROFILE_MEMORY_ENABLE_STRING 127
#define IDS_PROFILE_MEMORY_RANDOMIZE_STRING 128
#define IDR_MAINFRAME                   128
#define IDS_PROFILE_MEMORY_MIN_STRING   129
#define IDD_PROFILE_EDITOR_DIALOG       129
#define IDS_PROFILE_MEMORY_MAX_STRING   130
#define IDS_PROFILE_MEMORY_TRANSMIT_DATA_STRING 131
#define IDS_PROFILE_NETWORK_ENABLE_STRING 132
#define IDS_PROFILE_NETWORK_ENABLEPINGTEST_STRING 132
#define IDS_PROFILE_NETWORK_ENABLETCPCONTEST_STRING 133
#define IDS_PROFILE_NETWORK_PINGINTERVAL_STRING 134
#define IDS_PROFILE_NETWORK_PINGHOST_STRING 135
#define IDS_PROFILE_NETWORK_PINGTTL_STRING 136
#define IDS_CLIENT_HEADER_ID_STRING     137
#define IDS_CLIENT_HEADER_NAME_STRING   138
#define IDS_CLIENT_HEADER_IP_PORT_STRING 139
#define IDS_CLIENT_HEADER_STATUS_STRING 140
#define IDS_CLIENT_HEADER_PROFILE_STRING 141
#define IDS_BUTTON_CONFIGURE_CLIENT_STRING 142
#define IDS_BUTTON_CHANGE_PROFILE_STRING 143
#define IDS_BUTTON_START_SERVER_STRING  144
#define IDS_BUTTON_STOP_SERVER_STRING   145
#define IDS_BUTTON_LOG_VIEWER_STRING    146
#define IDS_PROFILE_MB_SAVE_CHANGES     150
#define IDS_PROFILE_MB_SAVE_CHANGES_STRING 150
#define IDS_PROFILE_MB_CANNOT_CONVERT_INT_STRING 151
#define IDS_PROFILE_MB_CANNOT_CONVERT_BOOL_STRING 152
#define IDS_PROFILE_MB_CANNOT_CONVERT_FLOAT_STRING 153
#define IDS_CLIENT_MB_CHANGE_PROFILE_STRING 154
#define IDS_ERROR_MB_LOGFILE            155
#define IDS_ERROR_MB_CONFIGFILE         156
#define IDS_PROFILE_NEW_NAME_STRING     157
#define IDS_PROFILE_NETWORK_PINGPAYLOAD_STRING 158
#define IDS_PROPERTIES_APPLY_CHANGES_STRING 159
#define IDS_PROFILE_NETWORK_PINGTRANSMITDATA_STRING 159
#define IDS_PROFILE_NETWORK_TCPCONINTERVAL_STRING 160
#define IDS_PROFILE_NETWORK_TCPCONHOST_STRING 161
#define IDS_PROFILE_NETWORK_TCPCONPORT_STRING 162
#define IDS_PROFILE_NETWORK_TCPCONTTL_STRING 163
#define IDS_PROFILE_NETWORK_TCPCONTRANSMITDATA_STRING 164
#define IDC_START_BUTTON                1000
#define IDC_STOP_BUTTON                 1001
#define IDC_INSTALL_BUTTON              1002
#define IDC_DELETE_BUTTON               1003
#define IDC_DB_TYPE_COMBO               1004
#define IDC_DB_IPADDRESS                1005
#define IDC_DB_PORT_EDIT                1006
#define IDC_DB_NAME_EDIT                1007
#define IDC_DB_USER_EDIT                1008
#define IDC_DB_PASS_EDIT                1009
#define IDC_LOG_RICHEDIT2               1010
#define IDC_APPLY_SETTINGS_BUTTON       1011
#define IDC_OPEN_SERVER_DIR_BUTTON      1012
#define IDC_OPEN_SERVER_DIR_BUTTON2     1013
#define IDC_EDIT_CONFIG_BUTTON          1013
#define IDC_PROFILE_EDITOR_BUTTON       1014
#define IDC_PROFILE_COMBO               1015
#define IDC_PROFILE_LIST                1016
#define IDC_SAVE_CHANGES_BUTTON         1017
#define IDC_PROFILE_LIST_EDIT           1018
#define IDC_LOG_STATIC                  1019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
